<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function getProjectAndTaskCount()
    {
        $results = $this->getEntityManager()
                ->createQuery(
                        'SELECT count(t) AS cont, p.name, p.id '
                        . 'FROM AppBundle:Project p '
                        . 'LEFT JOIN AppBundle:Task t With p.id = t.projectId '
                        . 'GROUP BY p.id')
                ->getResult();

        return $results;
    }

}
